<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Database1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SchoolSecurity" Member="SchoolSecurities">
    <Type Name="SchoolSecurity">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Info" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.HomeSafety" Member="HomeSafeties">
    <Type Name="HomeSafety">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Info" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.NiberHood" Member="NiberHoods">
    <Type Name="NiberHood">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Info" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.FirInfo" Member="FirInfos">
    <Type Name="FirInfo">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Info" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.AboutUs" Member="AboutUs">
    <Type Name="AboutUs">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Info" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.NewsFeed" Member="NewsFeeds">
    <Type Name="NewsFeed">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EnglishNews" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UrduNews" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.UseFullLinks" Member="UseFullLinks">
    <Type Name="UseFullLink">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Linkk" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.Home" Member="Homes">
    <Type Name="Home">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="welcomeInfo" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="cplcChiefInfo" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="img" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ContactUs" Member="ContactUs">
    <Type Name="ContactUs">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CplcSouth" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CplcWest" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CplcEast" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CplcCenteralv" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CplcMalir" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UanNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EmergencyNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FaxNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PhoneNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Criminal2" Member="Criminal2s">
    <Type Name="Criminal2">
      <Column Name="CriminalId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="FName" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CommittedCrime" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="WantedIn" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Details" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ImgUrl" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MuslimTown" Member="MuslimTowns">
    <Type Name="MuslimTown">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="month" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bike" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cars" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="street" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="kidnaping" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="murders" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="others" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="arressted" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="weppons" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>